export default function Head() {
  return (
    <>
      <title>nextjs13</title>
      <meta property="og:title" content="nextjs13!!" key="title" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
